---
- name: installation serveur apache
  hosts: apache2
  remote_user: batman
  become: yes
  become_method: sudo
  vars_files:
    - /etc/ansible/vars/vars.yml

  tasks:
    - name: Install Apache2 & Software
      package:
         name: "{{ item }}"
         state: latest

      with_items:
        - apache2
        - php
        - php-mysql
        - php-fpm
        - python3-mysqldb
        - unzip
        - default-mysql-client

    - name: Download WordPress
      get_url:
        url=https://wordpress.org/latest.tar.gz
        dest=/tmp/wordpress.tar.gz
        validate_certs=no

    - name: Extract WordPress
      unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/ copy=no
      become: yes

    - name: Update default Apache site
      become: yes
      lineinfile:
        dest=/etc/apache2/sites-enabled/000-default.conf
        regexp="(.)+DocumentRoot /var/www/html"
        line="DocumentRoot /var/www/wordpress"

    - name: Creation fichier conf Wordpress depuis le sample
      command: mv /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php creates=/var/www/wordpress/wp-config.php

    - name: remplissage fichier conf Wordpress avec infos db
      replace:
        path: /var/www/wordpress/wp-config.php
        regexp: "{{ item.regexp }}"
        replace: "{{ item.replace }}"
      with_items:
        - {regexp: 'database_name_here', replace: '{{mysql_db}}'}
        - {regexp: 'username_here', replace: '{{mysql_user}}'}
        - {regexp: 'password_here', replace: '{{mysql_password}}'}
        - {regexp: 'localhost', replace: '{{server_bdd}}'}

    - name: restart apache
      service:
        name: apache2
        state: restarted

    - name: Configuration passage par proxy pour Internet dans fichier environment
      lineinfile:
        path: /etc/environment
        line: 'http_proxy="http://{{ server_squid_haproxy }}:3128/"'

    - name: Reboot la machine pour reload les vars environment
      reboot:

    - name: regles iptables pour http https ssh mysql et squid
      command: "{{ item }} "
      with_items:
      - iptables -A INPUT -p tcp --dport http -j ACCEPT
      - iptables -A INPUT -p tcp --dport https -j ACCEPT
      - iptables -A INPUT -p tcp --dport ssh -j ACCEPT
      - iptables -A INPUT -p tcp --dport mysql -j ACCEPT
      - iptables -A INPUT -p tcp --dport 3128 -j ACCEPT
      - iptables -A OUTPUT -p tcp --dport http -j ACCEPT
      - iptables -A OUTPUT -p tcp --dport https -j ACCEPT
      - iptables -A OUTPUT -p tcp --dport ssh -j ACCEPT
      - iptables -A OUTPUT -p tcp --dport mysql -j ACCEPT
      - iptables -A OUTPUT -p tcp --dport 3128 -j ACCEPT
